## Multi Layer Neural Network

#### h1 and h2 are two units in hidden layer

The first layer shown on the bottom here are the inputs, understandably called the input layer. The middle layer is called the hidden layer, and the final layer (on the right) is the output layer. We can express this network mathematically with matrices again and use matrix multiplication to get linear combinations for each unit in one operation. For example, the hidden layer ($h_1$ and $h_2$ here) can be calculated

$$
\vec{h} = [h_1 \, h_2] = 
\begin{bmatrix}
x_1 \, x_2 \cdots \, x_n
\end{bmatrix}
\cdot 
\begin{bmatrix}
           w_{11} &amp; w_{12} \\
           w_{21} &amp;w_{22} \\
           \vdots &amp;\vdots \\
           w_{n1} &amp;w_{n2}
\end{bmatrix}
$$
The output for this small network is found by treating the hidden layer as inputs for the output unit. The network output is expressed simply

$$
y =  f_2 \! \left(\, f_1 \! \left(\vec{x} \, \mathbf{W_1}\right) \mathbf{W_2} \right)
$$

The number of hidden units a parameter of the network, often called a hyperparameter to differentiate it from the weights and biases parameters

In [3]:
#import pyTorch
import torch
def activation(x):
    return 1/(1+ torch.exp(-x))

In [4]:
#Generate some data
torch.manual_seed(7) #set the random seeds so things are predictible
#Creating feature vector
features = torch.randn((1,3))

#Define size of each layer in the network
n_input = features.shape[1]   # number of input units must match 
n_hidden = 2                  # number of hidden units
n_output = 1                  # number of output units

#Weights from input to hidden layer
w1 = torch.randn(n_input, n_hidden)
#Weights from hidden to output layer
w2 = torch.randn(n_hidden, n_output)

#Bias terms for hidden and output layer
B1 = torch.randn((1,n_hidden))
B2 = torch.randn((1,n_output))


In [8]:
hidden_output = activation(torch.mm(features,w1) + B1)
output = activation(torch.mm(hidden_output ,w2) + B2)
print(output)

tensor([[0.3171]])


## Numpy to Torch and back
Special bonus section! PyTorch has a great feature for converting between Numpy arrays and Torch tensors. To create a tensor from a Numpy array, use torch.from_numpy(). To convert a tensor to a Numpy array, use the .numpy() method.

In [9]:
import numpy as np
a = np.random.rand(4,3)
print(a)

[[0.7276185  0.7920595  0.6081663 ]
 [0.82972493 0.12551915 0.33593043]
 [0.35597365 0.18755575 0.36365027]
 [0.28455485 0.33333747 0.66910846]]


In [10]:
#Convert numpy array to tensor
b = torch.from_numpy(a)
print(b)

tensor([[0.7276, 0.7921, 0.6082],
        [0.8297, 0.1255, 0.3359],
        [0.3560, 0.1876, 0.3637],
        [0.2846, 0.3333, 0.6691]], dtype=torch.float64)


In [11]:
b.numpy()

array([[0.7276185 , 0.7920595 , 0.6081663 ],
       [0.82972493, 0.12551915, 0.33593043],
       [0.35597365, 0.18755575, 0.36365027],
       [0.28455485, 0.33333747, 0.66910846]])

#### The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.


In [13]:
#Changing tensor changes numpy array also
b.mul_(2)
print(a)
print(b)

[[2.910474   3.168238   2.43266519]
 [3.31889972 0.50207659 1.34372172]
 [1.42389461 0.75022299 1.45460107]
 [1.13821941 1.3333499  2.67643385]]
tensor([[2.9105, 3.1682, 2.4327],
        [3.3189, 0.5021, 1.3437],
        [1.4239, 0.7502, 1.4546],
        [1.1382, 1.3333, 2.6764]], dtype=torch.float64)
